# Generated by Django 4.1.6 on 2023-04-24 13:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0002_cart_cartitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="image",
            field=models.ImageField(
                default="static/categories/default.png", upload_to="static/categories/"
            ),
        ),
    ]
